ORGANIZATION_BLOCK "COMPLETE RESTART"
TITLE = "Complete Restart"
{ S7_Optimized_Access := 'FALSE' }
VERSION : 0.1
   VAR_TEMP 
      OB100_EV_CLASS : Byte;   // 16#13, Event class 1, Entering event state, Event logged in diagnostic buffer
      OB100_STRTUP : Byte;   // 16#81/82/83/84 Method of startup
      OB100_PRIORITY : Byte;   // Priority of OB Execution
      OB100_OB_NUMBR : Byte;   // 100 (Organization block 100, OB100)
      OB100_RESERVED_1 : Byte;   // Reserved for system
      OB100_RESERVED_2 : Byte;   // Reserved for system
      OB100_STOP : Word;   // Event that caused CPU to stop (16#4xxx)
      OB100_STRT_INFO : DWord;   // Information on how system started
      OB100_DATE_TIME : Date_And_Time;   // Date and time OB100 started
   END_VAR

BEGIN
    
    // =========================================================================
    // ИНИЦИАЛИЗАЦИЯ ТЕХНОЛОГИЧЕСКИХ ПАРАМЕТРОВ И КОЭФФИЦИЕНТОВ SYMAP
    // =========================================================================
    // Эта функция выполнится строго ОДИН РАЗ при переходе CPU из STOP в RUN.
    // Она проверит все 85 коэффициентов Factor для каждого из 30 устройств.
    // Если коэффициент равен 0.0, он автоматически инициализируется значением 1.0.
    // Если значение уже было изменено оператором (не 0.0), оно останется нетронутым.
    
    "FC_InitFactors"(); 

END_ORGANIZATION_BLOCK

