DATA_BLOCK "Read_write_Symap_Db"
VERSION : 0.1
// Глобальный блок данных Stucke SYMAP
STRUCT 
    Devices : Array[1..30] of STRUCT
        In  : "UDT_Symap_In";          // Данные чтения
        Out : "UDT_Symap_OUT_b0_15";   // Данные записи
        Raw_Real      : Array[1..41] of Real; // Мгновенные значения входов  в Real
        Filtered_Real : Array[1..41] of Real; // Усредненные значения входов в Real
    END_STRUCT;
END_STRUCT;

BEGIN
END_DATA_BLOCK